// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_movie/test/presentation/viewmodel/movie_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_movie/domain/entities/movie.dart' as _i5;
import 'package:flutter_movie/domain/repositories/movie_repository.dart' as _i2;
import 'package:flutter_movie/domain/usecases/get_movies_usecase.dart' as _i3;
import 'package:flutter_movie/domain/usecases/refresh_movies_usecase.dart'
    as _i6;
import 'package:flutter_movie/domain/usecases/update_favorite_status_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMoviesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesUseCase extends _i1.Mock implements _i3.GetMoviesUseCase {
  MockGetMoviesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
        Invocation.getter(#movieRepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movieRepository),
        ),
      ) as _i2.MovieRepository);

  @override
  _i4.Stream<List<_i5.Movie>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Movie>>.empty(),
      ) as _i4.Stream<List<_i5.Movie>>);
}

/// A class which mocks [RefreshMoviesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshMoviesUseCase extends _i1.Mock
    implements _i6.RefreshMoviesUseCase {
  MockRefreshMoviesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
        Invocation.getter(#movieRepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movieRepository),
        ),
      ) as _i2.MovieRepository);

  @override
  _i4.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UpdateFavoriteStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateFavoriteStatusUseCase extends _i1.Mock
    implements _i7.UpdateFavoriteStatusUseCase {
  MockUpdateFavoriteStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
        Invocation.getter(#movieRepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movieRepository),
        ),
      ) as _i2.MovieRepository);

  @override
  _i4.Future<void> call(_i5.Movie? movie) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [movie],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
